Vagrant.configure("2") do |config|

  # Define a imagem do sistema operacional
  config.vm.box = "ubuntu/xenial64"

  # Define o nome de host da máquina
  config.vm.hostname = "servidor-vagrant"

  # Configuração de recursos
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
  end

  # Configuração de rede privada (IP Estático)
  config.vm.network "private_network", ip: "192.168.56.10"

  # onfiguração de rede pública (Bridge)
  config.vm.network "public_network", 
    bridge: [
      "Wi-Fi",
      "Ethernet",
      "Realtek PCIe GbE Family Controller"
    ],
    use_dhcp_assigned_default: true
end