Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "servidor-arquivos"

  # Compartilha a pasta "site" do host com "/var/www/html" na VM
  config.vm.synced_folder "./site", "/var/www/html"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
  end

end
