Vagrant.configure("2") do |config|

  # Define a box que será utilizada
  config.vm.box = "ubuntu/jammy64"
   
  # Aplicando a arquitetura amd64 para a box (tentei utilizar esse, mas tive erros que não consegui resolver, então comentei)
  #config.vm.box_architecture = "amd64"

  # Aplicando o tempo limite de boot em segundos 
  config.vm.boot_timeout = 600

  # Impede o Vagrant de ficar buscando atualizações da box na internet toda vez que você der um 'vagrant up' (deixa mais rápido)
  config.vm.box_check_update = false

  # Define o nome da máquina
  config.vm.hostname = "servidor-vagrant"

  # Encaminha a porta 80 da VM para a porta 8080 do computador
  config.vm.network "forwarded_port", guest: 80, host: 8080

  # Configura os recursos da máquina virtual (1GB RAM e 1 CPU)
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
  end

end