Vagrant.configure("2") do |config|
  # 1. Define o sistema operacional (Ubuntu)
  config.vm.box = "ubuntu/focal64"
  
  # 2. Define um nome limpo para a máquina na rede
  config.vm.hostname = "servidor-devops"

  # 3. Configura o hardware da máquina no VirtualBox (Limita a RAM para 1GB)
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.name = "VM_Grupo3_Pedro"
  end
end