Vagrant.configure("2") do |config|

  # Define a box que será utilizada
  config.vm.box = "ubuntu/jammy64"

  # Define o nome da máquina
  config.vm.hostname = "servidor-web"

  # Encaminha a porta 80 da VM para a porta 8080 do computador
  config.vm.network "forwarded_port", guest: 80, host: 8080

  # Configura os recursos da máquina virtual
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
  end

  # Instala o Apache automaticamente
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y apache2
  SHELL

end
