Vagrant.configure("2") do |config|

  # Máquina 1: servidor web
  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/jammy64"
    web.vm.hostname = "web"
    web.vm.network "forwarded_port", guest: 80, host: 8080
    web.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
  end

  # Máquina 2: banco de dados
  config.vm.define "db" do |db|
    db.vm.box = "ubuntu/jammy64"
    db.vm.hostname = "db"
    db.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
  end

end
